server:
  port: ${PORT_TO_EXPOSE:8080}

logging:
  level:
    ROOT: INFO
    org.springframework: INFO

upload:
  path: C:\Users\FORTRIX\Desktop\coffee_shop\uploads

spring:
  flyway:
    baselineOnMigrate: true
    enabled: true
  application:
    name: MARVELS_SHOP
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/marvels?currentSchema=public
    username: postgres
    password: password
  jpa.hibernate.ddl-auto: none
  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.mail.ru
    port: 465
    username: marvels-order@mail.ru
    password: UfZ75f8f5rxs7HYYyZ67
    protocol: smtps
    properties:
      mail:
        debug: false
        starttls:
          enable: true
        smtp:
          auth: true
        transport:
          protocol: smtps

secure:
  signingKey: sign_key_for_jwt

springfox:
  documentation:
    swagger:
      v2:
        path: /v3/api-docs